Name:           ros-jade-pyros
Version:        0.3.2
Release:        0%{?dist}
Summary:        ROS pyros package

Group:          Development/Libraries
License:        BSD
Source0:        %{name}-%{version}.tar.gz

Requires:       python-mock >= 1.0.1
Requires:       python-six >= 1.5.2
Requires:       ros-jade-pyros-config >= 0.1.3
Requires:       ros-jade-pyros-utils >= 0.1.2
Requires:       ros-jade-pyzmp >= 0.0.14
Requires:       ros-jade-rospy >= 1.11.19
Requires:       ros-jade-std-msgs >= 0.5.10
Requires:       ros-jade-std-srvs >= 1.11.2
BuildRequires:  python-mock >= 1.0.1
BuildRequires:  python-six >= 1.5.2
BuildRequires:  ros-jade-catkin >= 0.6.18
BuildRequires:  ros-jade-catkin-pip >= 0.2.0
BuildRequires:  ros-jade-pyros-config >= 0.1.3
BuildRequires:  ros-jade-pyros-test >= 0.0.6
BuildRequires:  ros-jade-pyros-utils >= 0.1.2
BuildRequires:  ros-jade-pyzmp >= 0.0.14
BuildRequires:  ros-jade-rosnode >= 1.11.19
BuildRequires:  ros-jade-rospy >= 1.11.19
BuildRequires:  ros-jade-rosservice >= 1.11.19
BuildRequires:  ros-jade-rostest >= 1.11.19
BuildRequires:  ros-jade-rostopic >= 1.11.19
BuildRequires:  ros-jade-rosunit >= 1.11.12

%description
Provides Python to ROS multiprocess API, useful for using ROS from different
multiprocess environment (think webserver, celery, etc.) while keeping both
isolated.

%prep
%setup -q

%build
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/jade/setup.sh" ]; then . "/opt/ros/jade/setup.sh"; fi
mkdir -p obj-%{_target_platform} && cd obj-%{_target_platform}
%cmake .. \
        -UINCLUDE_INSTALL_DIR \
        -ULIB_INSTALL_DIR \
        -USYSCONF_INSTALL_DIR \
        -USHARE_INSTALL_PREFIX \
        -ULIB_SUFFIX \
        -DCMAKE_INSTALL_LIBDIR="lib" \
        -DCMAKE_INSTALL_PREFIX="/opt/ros/jade" \
        -DCMAKE_PREFIX_PATH="/opt/ros/jade" \
        -DSETUPTOOLS_DEB_LAYOUT=OFF \
        -DCATKIN_BUILD_BINARY_PACKAGE="1" \

make %{?_smp_mflags}

%install
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/jade/setup.sh" ]; then . "/opt/ros/jade/setup.sh"; fi
cd obj-%{_target_platform}
make %{?_smp_mflags} install DESTDIR=%{buildroot}

%files
/opt/ros/jade

%changelog
* Thu Mar 23 2017 AlexV <asmodehn@gmail.com> - 0.3.2-0
- Autogenerated by Bloom

* Fri Jan 13 2017 AlexV <asmodehn@gmail.com> - 0.3.1-0
- Autogenerated by Bloom

* Wed Nov 23 2016 AlexV <asmodehn@gmail.com> - 0.3.0-1
- Autogenerated by Bloom

* Mon Nov 21 2016 AlexV <asmodehn@gmail.com> - 0.3.0-0
- Autogenerated by Bloom

